### ISSUE TITLE
14_bert.py出错

### ISSUE THREAD

**Issue by wwwjs** [yanqiangmiffy/Food-Safety-Review#1]
您好，我在运行14_bert.py时出现了下面的出错，请问怎么解决呀？
Epoch 4/4
1000/1000 [==============================] - 2289s 2s/step - loss: 0.0125 - acc: 0.9959   
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2001/2001 [03:54<00:00,  8.54it/s]
/home/sjwang/py/python3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
I1222 22:47:49.886529 140004958238528 14_bert.py:159] lr: 0.000010, epoch: 3, score: 0.8685, acc: 0.8486, f1: 0.4590,best: 0.8685

Traceback (most recent call last):
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 768 and 1024. Shapes are [768,1] and [1024,1]. for 'Assign_198' (op: 'Assign') with input shapes: [768,1], [1024,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "14_bert.py", line 217, in <module>
    model.load_weights('./models/bert{}.w'.format(fold))
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/keras/engine/network.py", line 1217, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/keras/engine/saving.py", line 1199, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2727, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1952, in assign
    name=name)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/home/sjwang/py/python3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 768 and 1024. Shapes are [768,1] and [1024,1]. for 'Assign_198' (op: 'Assign') with input shapes: [768,1], [1024,1].

**Comment by wwwjs** [comment]
不好意思呀，我在同时运行bert和roberta时忘了修改文件名，失误失误，嘿嘿嘿
